### ISSUE TITLE
Plot Home Range

### ISSUE THREAD

**Issue by PieterjanVerhelst** [PieterjanVerhelst/resident-eel-polder-analysis#7]
The script to plot the home range (plot_homerange.R) does not give the number of eels per home range. Namely, an error with the 'aes' occurs: 'Error: Aesthetics must be either length 1 or the same as the data (3): x, y, label'. In addition, is it possible to switch the order of the plots: Pond - Canal - Polder?
PS: this script is fully functional on its own (data is uploaded in this script).

**Comment by PieterjanVerhelst** [comment]
Closed it to fast. The number of eels is not yet given on top of the boxplots

**Comment by stijnvanhoey** [comment]
Based on the current master branch, when running the code:

![home_range_boxplot](https://cloud.githubusercontent.com/assets/754862/22641826/91cd6acc-ec58-11e6-9b2e-5f6e12db4e6d.png)
